name: Reusable workflow

on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Vem där?'
        type: string
        required: true
        default: Alex
    outputs:
      time:
        description: 'The time when greeting.'
        value: ${{ jobs.reusable-job.outputs.time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }}
    steps: 
      - name: Say hello
        run: echo "Tjena ${{ inputs.who-to-greet }} "

      - name: Tid
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

        
    
